### ISSUE TITLE
Infinite Loop on AdapterHandler.adaptOut method.

### ISSUE THREAD

**Issue by stuntguy3000** [mkotb/ConfigAPI#10]
```
java.lang.StackOverflowError
        at java.util.Vector.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.util.Vector.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner$1.run(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner.defineClass(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator.generate(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator.generateSerializationConstructor(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ReflectionFactory.generateConstructor(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ReflectionFactory.newConstructorForSerialization(Unknown Source) ~[?:1.8.0_121]
        at xyz.mkotb.configapi.internal.InternalsHelper.newInstanceWithoutInit(InternalsHelper.java:55) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:147) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
```

@mkotb I've made the relevant code and logs to you available at https://github.com/stuntguy3000/ConfigAPI-Issue

Any help is much appreciated as I'm unsure what exactly is going on.

Cheers.

**Comment by mkotb** [comment]
The issue here is that your class fields are static when they aren't supposed to be. Here's an example of a working config model:

```java
@Comment("This is my header comment")
public class MyConfig {
    private String startMessage = "This awesome bukkit plugin has started!";
    @Comment("Put in your favourite number here!")
    @RequiredField
    private int myFavouriteNumber = 3;
}
```

For reference, this is what you did
```java
@Comment("This is my header comment")
public class MyConfig {
    public static String startMessage = "This awesome bukkit plugin has started!";
    @Comment("Put in your favourite number here!")
    @RequiredField
    public static int myFavouriteNumber = 3;
}
```

**Comment by stuntguy3000** [comment]
Thanks for those changes @mkotb, but I have ran into a new issue when using a ``HashMap``.

Currently using the repository's source code and not maven (maven repo is outdated).

```Java
// Configuration Class
public class BlockDropsConfig {
    @Comment({"Block Drop Configurations","","Block Format: <Material ID>;<Block Data>"})
    private HashMap<String, String> testMap = new HashMap<>();
}

// Load Method
config = getPlugin().getConfigHandler().getConfigFactory().fromFile(getModuleName(), BlockDropsConfig.class);
```

Stacktrace:
```
[18:52:00 ERROR]: Error occurred while enabling TimeWarp-Utilities v1.0 (Is it up to date?)
java.lang.StackOverflowError
        at java.util.Vector.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.util.Vector.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner$1.run(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner.defineClass(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator.generate(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator.generateSerializationConstructor(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ReflectionFactory.generateConstructor(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ReflectionFactory.newConstructorForSerialization(Unknown Source) ~[?:1.8.0_121]
        at xyz.mkotb.configapi.internal.InternalsHelper.newInstanceWithoutInit(InternalsHelper.java:55) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:147) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        [...]
```

**Comment by mkotb** [comment]
Although this shouldn't be happening, can you try making the field type `Map<String, String>` and not making it implementation specific?

**Comment by stuntguy3000** [comment]
Changed to 
```java
private Map<String, String> testMap = new HashMap<>();
```

Issue still persists unfortunately.

**Comment by stuntguy3000** [comment]
@mkotb Any updates?

**Comment by mkotb** [comment]
@stuntguy3000 is that the full stacktrace

**Comment by stuntguy3000** [comment]
@mkotb 

Indeed.

**"New" Sample Code:**
```java
@NoArgsConstructor
@Data
public class DemoConfig {
        @Comment({"Demo Config"})
        private HashMap<String, String> testMap = new HashMap<>();
}
```

**Full-er stacktrace:**
```[16:30:19 ERROR]: Error occurred while enabling TimeWarp-Utilities v1.0 (Is it up to date?)
java.lang.StackOverflowError
        at java.util.Vector.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.util.Vector.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingClassLoader.<init>(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner$1.run(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.reflect.ClassDefiner.defineClass(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator.generate(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.MethodAccessorGenerator.generateSerializationConstructor(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ReflectionFactory.generateConstructor(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.ReflectionFactory.newConstructorForSerialization(Unknown Source) ~[?:1.8.0_121]
        at xyz.mkotb.configapi.internal.InternalsHelper.newInstanceWithoutInit(InternalsHelper.java:55) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:147) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptOut(AdapterHandler.java:193) ~[?:?]
        [...]
```

**Comment by mkotb** [comment]
@stuntguy3000 again, why are you using `HashMap<K,V>` as your field type?

**Comment by stuntguy3000** [comment]
Being totally honest, I haven't actually considered how a HashMap is meant to translate properly to YAML.

As for the use case, in one particular instance to achieve this type of system:

```yaml

profiles:
        profile1:
                setting1: true
                setting2: false
                setting3: 2
        profile2:
                setting1: false
                setting2: false
                setting3: 1
        [...]

```

**Comment by mkotb** [comment]
It works by creating a ConfigurationSection with its keys and values matching the ones in memory.

For your use case, I would recommend (basing off of OOP) using a `List<Profile>` and within that if you want to just contain settings in the `Profile` class that works as well.

sorry accidentally clicked comment & close

**Comment by stuntguy3000** [comment]
That should work fine, I'll make the changes and let you know how I go.

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/27003388-bc1b993c-4e34-11e7-992e-523859590b64.png)

@mkotb Any immediate ideas or possible causes that come to mind?

A few values are set to null (referencing a static variable set to null), could this be a factor?

**Comment by mkotb** [comment]
I have no idea what you're doing that's causing this issue. I just tried using a `Map` with a string as a key and it worked just fine.

Here's what I did:

```java
// MyConfig.java
public class MyConfig {
  // other fields are here
    private Map<String, PartOfConfig> testMap = new HashMap<>();

    // called on start, just filling map with data
    public void fillSelf() {
        testMap.put("cat", new PartOfConfig());
        testMap.put("dog", new PartOfConfig());
        testMap.put("america", new PartOfConfig());
    }
}

// PartOfConfig.java
public class PartOfConfig {
    private String hi = "my name is billy";
}
```

When I start and stop my server, this is saved:
```yml
test-map:
  cat:
    hi: my name is billy
  dog:
    hi: my name is billy
  america:
    hi: my name is billy
```

**Comment by stuntguy3000** [comment]
One thing I am doing (which I don't normally do) is using static hashmaps as "default" values - some of which are null.

I'll keep playing around.

Cheers

**Comment by mkotb** [comment]
What do you mean? This behavior in the runtime is important for me to know so I can help you

**Comment by stuntguy3000** [comment]
[Here](https://github.com/stuntguy3000/ConfigAPI-Issue/blob/master/engine/config/BlockDropsModuleConfig.java) is the config file I'm trying to save.

A good example of the default values is [here](https://github.com/stuntguy3000/ConfigAPI-Issue/blob/master/engine/config/BlockConfig.java).

**Comment by stuntguy3000** [comment]
@mkotb Still having issues trying to resolve/workaround this issue. No idea what's causing it. _fun_

**Comment by mkotb** [comment]
Consider it's possible that there is a self reference so resolving results
in an infinite loop. I'd recommend you look into that in your model. Could
you show me an expected output with default values?

**Comment by stuntguy3000** [comment]
As of current I do not actually have a planned yml outcome, but if i need to further down the line i might write one up.

I will investigate self referencing.

**Comment by mkotb** [comment]
I was just suggesting writing a planned outcome to help figure out if there
is a self referencing issue

**Comment by stuntguy3000** [comment]
I seemed to be doing some weird loading issues which are now resolved.

However, a new error has appeared.

When *loading* this class:
```java
@Data
@AllArgsConstructor
public class ItemDropMetaSettings {
    @RequiredField
    @Comment("The minimum amount of drops a player can receive")
    private int minimumDrops = 1;
    @Comment("The maximum amount of drops a player can receive")
    private int maximumDrops = 1;
    @Comment("Allows a user to receive more a drop more than once in a single block break.")
    private boolean allowRepeatedDrops = false;
}
```

This lovely NPE appears (trimmed)
```
java.lang.NullPointerException
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Field.set(Unknown Source) ~[?:1.8.0_121]
        at xyz.mkotb.configapi.internal.InternalsHelper.setField(InternalsHelper.java:139) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptIn(AdapterHandler.java:315) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptIn(AdapterHandler.java:315) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptIn(AdapterHandler.java:315) ~[?:?]
        at xyz.mkotb.configapi.internal.adapt.AdapterHandler.adaptIn(AdapterHandler.java:232) ~[?:?]
        at xyz.mkotb.configapi.ConfigFactory.fromFile(ConfigFactory.java:86) ~[?:?]
        at xyz.mkotb.configapi.ConfigFactory.fromFile(ConfigFactory.java:60) ~[?:?]
        at me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.BlockDropsModule.loadConfig(BlockDropsModule.java:49) ~[?:?]
        at me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.handlers.DropsHandler.importConfiguration(DropsHandler.java:37) ~[?:?]
        at me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.BlockDropsModule.registerHandlers(BlockDropsModule.java:38) ~[?:?]
        [... bukkit/minecraft removed]
```

Now, doing some quick debugging to your lib by modifying the setField method in InternalsHelper to be
```java
public static boolean setField(Field field, Object instance, Object value) {
        try {
            System.out.println("Setting " + field + " to " + value + " from " + instance);
            field.setAccessible(true);
            field.set(instance, value);
            return true;
        } catch (IllegalAccessException ex) {
            return false;
        }
    }
```

Reveals some interesting stuff. 
```
[11:36:32 INFO]: Setting private java.util.Map me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.engine.config.BlockDropsModuleConfig.blockDrops to {} from BlockDropsModuleConfig(blockDrops={}, demoConfig=BlockConfig(block=null, toolSettings=ToolSettings(allowedTools=[], illegalToolSettings=null, toolsList=[]), itemDropMetaSettings=ItemDropMetaSettings(minimumDrops=1, maximumDrops=1, allowRepeatedDrops=false), itemDropSettings=null, experienceSettings=null, filterConfig=null), filterExecutions={})
[11:36:32 INFO]: Setting private java.util.List me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.engine.config.settings.ToolSettings.allowedTools to [] from ToolSettings(allowedTools=[], illegalToolSettings=null, toolsList=[])
[11:36:32 INFO]: Setting private me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.engine.config.settings.ToolSettings me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.engine.config.BlockConfig.toolSettings to ToolSettings(allowedTools=[], illegalToolSettings=null, toolsList=[]) from BlockConfig(block=null, toolSettings=ToolSettings(allowedTools=[], illegalToolSettings=null, toolsList=[]), itemDropMetaSettings=ItemDropMetaSettings(minimumDrops=1, maximumDrops=1, allowRepeatedDrops=false), itemDropSettings=null, experienceSettings=null, filterConfig=null)
[11:36:32 INFO]: Setting private int me.stuntguy3000.clients.skyservers.timewarputilities.modules.blockdrops.engine.config.settings.ItemDropMetaSettings.minimumDrops to 1 from null
```

That last log line is before the stacktrace.

The kicker? It's writing to the config file as expected.

![image](https://user-images.githubusercontent.com/1522389/27007701-0a236248-4e9b-11e7-9e4c-09bcd0d6ae35.png)

Cheers @mkotb

**Comment by mkotb** [comment]
@stuntguy3000 you need to have a default constructor for the class. That was my first guess and I looked further into my and your code to make sure.

As it seems like all else is working, I'm going to close this issue.

**Comment by stuntguy3000** [comment]
@mkotb 

Unfortunately not. The same AdaptOut error reappears when trying to save the HashMap **when containing data**.

[Save Function](
https://github.com/stuntguy3000/ConfigAPI-Issue/blob/master/me/stuntguy3000/clients/skyservers/timewarputilities/modules/blockdrops/BlockDropsModule.java#L74)

[BlockDropsModuleConfig](https://github.com/stuntguy3000/ConfigAPI-Issue/blob/master/me/stuntguy3000/clients/skyservers/timewarputilities/modules/blockdrops/engine/config/BlockDropsModuleConfig.java)

[BlockConfig Data File](https://github.com/stuntguy3000/ConfigAPI-Issue/blob/master/me/stuntguy3000/clients/skyservers/timewarputilities/modules/blockdrops/engine/config/BlockConfig.java)

Will keep experimenting.

**Comment by mkotb** [comment]
@stuntguy3000 Map saving and loading work as per my tests above, so unless you have a typed type such as `Map<String, List<String>>` then there shouldn't be any issues with it.

My best recommendation is to work your way down removing fields from BlockConfig until the stack trace does not occur. Then from there, go down into that class and repeat until you find a supported type (String, primitives, maps, collections, etc.) which is causing the issue. 

I believe it goes without saying that if you removed all the fields from a class and an empty class is causing an error, it's likely a similar issue to the one you just had.

**Comment by stuntguy3000** [comment]
I still don't know why it's even causing the issue with the saving - i can't see any issues. Ill keep digging into this or simply give up.

**Comment by stuntguy3000** [comment]
I've attempted to use this API a few times - and I always run across this very issue. I can't seem to understand what's going wrong every time.
